<? 
/*
 * $Source: /home/xubuntu/berlios_backup/github/tmp-cvs/otmp/Repository/Release1/help/templates/faq.inc,v $
 * $Revision: 1.1 $
 * $Id: faq.inc,v 1.1 2001/12/17 18:28:31 hifix Exp $
 */
?> 
<h3>Die am h&auml;ufig gestalten Fragen/Antworten </h3>
<h4>1. Sind nur die Menschen aus den Entwicklungsl&auml;nder befugt Texte zum &uuml;bersetzten frei zu geben?</h4>
Nein das System wurde zwar mit dem Schwerpunkt Entwicklungsl&auml;nder entwickelt, aber jeder kann sich bei uns anmelden! 
<h4>2. Was ist OTMP kurz?</h4>
OTMP ist wie der name eigentlich schon verr&auml;t, ein Online Sprach Markt Platz, wo man entweder zu einem bestimmten Thema sich Texte herunter-laden kann oder 
eine bestimmten Text zum &Uuml;bersetzten beauftragt! 
<h4>3. Wof&uuml;r steht OTMP?</h4>
Online Translation Market Place 
<h4>4. Was mach man, wenn keine eigene Email-Adresse vorhanden ist!</h4>
Die M&ouml;glich haben wir bereit in Betracht gezogen! Daf&uuml;r gibt es bei uns eine spezielle Anleitung, f&uuml;r die Menschen, die keine eigene E.-Adresse 
haben! 
<h4>5. Ist es auch m&ouml;glich einen Text in verschiedenen Sprache &uuml;bersetzten zu lassen? </h4>
Das wird bei uns dem User frei gestellt ,in welche und wieviele Sprache er/sie den Text &uuml;bersetzen lassen m&ouml;chte! Man mu&szlig; lediglich die Wunschsprachen, 
in der dann der Text &uuml;bersetzt wird, angeben! 
<h4>6. Kann man auch Texte herunter-laden ohne, da&szlig; man bei OTMP angemeldet st? </h4>
Zum herunterladen von Texten mu&szlig; man sich nicht extra anmelden. Aber sobald man einen Auftrag zum &uuml;bersetzen hat, wird eine Anmeldung vorausgesetzt! 
Ist man nicht angemeldet, so mu&szlig; man sich dann erst anmelden! 
<h4>7. Kann man sicher avon ausgehen, da&szlig; der Auftrag zum dem angegebenen Frist auch bearbeitet wird! </h4>
Leider nicht! Denn das h&auml;ngt ganz allein davon ab, ob sich ein &Uuml;bersetzer f&uuml;r diesen bestimmten Text &quot;finden&quot; l&auml;&szlig;t! Denn die &Uuml;bersetzerdaten 
(Kategorie, Sprache) m&uuml;ssen mit der Daten in der der Text &uuml;bersetzt wird &uuml;bereinstimmen! 
