<? 
/*
 * $Source: /home/xubuntu/berlios_backup/github/tmp-cvs/otmp/Repository/Release1/help/templates/help.inc,v $
 * $Revision: 1.1 $
 * $Id: help.inc,v 1.1 2001/12/17 18:28:31 hifix Exp $
 */
?>
<!-- doc body -->
<p>Hilfe gibt es unter folgenden Links:</p>
<ul>
  <li><a href="what.php">Was ist OTMP ?</a></li>
  <li> <a href="faq.php">H&auml;ufig gestellte Fragen</a></li>
  <li><a href="contact.php?origin=help">Kontakt zur OTMP-Crew</a></li>
</ul>
<!-- doc body end -->

