<? 
/*
 * $Source: /home/xubuntu/berlios_backup/github/tmp-cvs/otmp/Repository/Release1/help/templates/whatis.inc,v $
 * $Revision: 1.1 $
 * $Id: whatis.inc,v 1.1 2001/12/17 18:28:31 hifix Exp $
 */
?>
<h2>Was ist OTMP? </h2>
<p>
  Ein Drittel der ca. 6500 Sprachen, die zur Zeit noch weltweit gesprochen werden, 
  wird innerhalb der n&auml;chsten <br>
  Jahrzehnte aussterben. Pessimistische Sch&auml;tzungen gehen sogar davon aus, 
  da&szlig; im Laufe dieses Jahrhunderts bis zu <br>
  90 % der jetzt noch gesprochenen Sprachen aussterben k&ouml;nnten. Sprachen 
  und Dialekte sind nicht nur <br>
  Auspr&auml;gungen menschlicher Kultur und menschlichen Geistes, sondern auch 
  Mittel der Welterschlie&szlig;ung und des <br>
  Sozialkontakts f&uuml;r ihre Sprecher. Sie stellen einen Wert an sich dar und 
  sollten deshalb - auch als Manifestationen der <br>
  Kreativit&auml;t und der Vielfalt des menschlichen Geistes - erhalten und dokumentiert 
  werden. <br>
  Eine verschiedene Vielfalt dieser Kreativit&auml;t und und auch verschiedene 
  Sprachen/Dialekte sind in den Entwicklungsl&auml;nder zu finden! <br>
  &quot;Online Translation Market Place&quot; OTMP ist ein System, das es sich 
  zum Ziel gesetzt hat, ein Sprach Markt Platz zu entwickeln, mit dem gro&szlig;en 
  Schwerpunkt Entwicklungsl&auml;nder! <br>
  Somit ist es klar, da&szlig; man Open Source betreiben mu&szlig;, besonders 
  um die in den L&auml;ndern lebenden &quot;armen&quot; menschen ansprechen zu 
  k&ouml;nnen! <br>
  Dennoch schlie&szlig;en wir niemanden au Grund der Herkunft aus, nat&uuml;rlich 
  auch nicht die den &quot;Industriel&auml;nder&quot; lebende Menschen! <br>
  Jeder kann sich bei uns anmelden uns als User x in dem System erfa&szlig;t werden! 
  <br>
  OTMP erhofft sich damit eine interkulturelle Verbindung auf der geistigen Ebene 
  der Kreativit&auml;t, Intelligenz Kultur und Sprachen! <br>
  Also besteht OTMP aus eine Vielfalt von interkulturellen Menschen/User ,die 
  nur einen Ziel verfolgen, n&auml;mlich ihre wissenschaftlichen, Texte in welcher 
  Kategorie auch immer, entweder zu ver&ouml;ffentlichen oder auch zum &Uuml;bersetzen 
  &quot;frei&quot; geben! <br>
  Damit jeder gleichberechtigt ist, wollen wir nur die Gruppe von Menschen f&ouml;rdern, 
  die von vornherein benachteiligt sind! <br>
  Wir freuen uns auf jeden User, aus welcher Herkunft er/sie auch sein mag! </p>
<p><br>
  Viel Spa&szlig;, Freude ... mit OTMP!!!! </p>




