<h3>Willkommen bei OTMP - Ihrem &Uuml;bersetzungsdienst!</font></h3>

<p>OTMP ist eine offene &Uuml;bersetzungsplattform. Auf OTMP können sie Ihre
Dokumente veröffentlichen und in verschiedene andere Sprachen &uuml;bersetzen
lassen.</p>

<p>Dokumente bezeichnet hierbei sowohl Artikel, Ausarbeitungen, Bücher, Skripte,
Prosa, Diplomarbeiten, einfache Schriften, Liebesbriefe, sonstige Texte und mehr.</p>

<p>Wenn auch sie diesen Service nutzen m&ouml;chten, so m&uuml;ssen sie sich
hierf&uuml;r nur anmelden. Die Anmeldung ist kostenlos und ihre Daten werden nicht
an andere Personen weitergegeben. Nachdem sie sich angemeldet haben, k&ouml;nnen
sie sowohl Dokumente für &Uuml;bersetzungen ablegen als auch welche &Uuml;bersetzen.</p>

<p>OTMP ist auf gute &Uuml;bersetzer angewiesen, und daher stets auf der Suche
nach neuen &Uuml;bersetzern. Lesen sie weiter, wenn sie wissen wollen, welche
Vorteile ihnen das Arbeiten als &Uuml;bersetzer bringt.</p>

<p>Wir w&uuml;nschen Ihnen viel Spass und Erfolg mit unserem System!</p>
