<h2>Text download</h2>
<form method="post" action="">
  <table width="100%" cellspacing="1" cellpadding="2">
    <tr> 
      <td>runterzuladener Text:</td>
      <td>TITEL</td>
      <td>&nbsp;</td>
    </tr>
    <tr> 
      <td>Sprache:</td>
      <td>DE</td>
      <td>&nbsp;</td>
    </tr>
    <tr> 
      <td>m&ouml;chten Sie es gepackt?<br>
        w&auml;hlen Sie einen Packer aus</td>
      <td> 
        <select name="filetype">
          <option value="0" selected>kein Packer</option>
          <option value="1">.zip</option>
          <option value="2">.tar</option>
        </select>
      </td>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td>
        <input type="submit" name="Submit" value="File runterladen">
      </td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
    </tr>
  </table>
</form>
