<h3>&Uuml;bersetzungsauftrag f&uuml;r den Text annehmen</h3>
Mit dem herunterladen des Textes (Originalsprache) werden Sie als &Uuml;bersetzer des Textes im System eingetragen. <br>
Klicken Sie dazu auf die unterstehende Schaltfl&auml;che "Datei runterladen". Wenn Sie diesen Text nicht &uuml;bersetzen wollen, klicken sie <a href="<?=$CFG->wwwroot?>/docs/document.php?id=<?=$id?>">hier</a>.
<br><br>