<?
/*
 * $Source: /home/xubuntu/berlios_backup/github/tmp-cvs/otmp/Repository/Release1/docs/templates/upload_success.inc,v $
 * $Revision: 1.2 $
 * $Id: upload_success.inc,v 1.2 2001/12/10 10:15:49 hifix Exp $
 *
 * To Do:
 * - LOcalisation
 * - ALL
 */
 ?>
 <p>Text wurde erfolgreich ins System gestellt.<br>
</p>
<p>Bitte w&auml;hlen Sie jetzt die Sprachen in welche der Text &uuml;bersetzt 
  werden soll ..</p>