<?
/*
 * $Source: /home/xubuntu/berlios_backup/github/tmp-cvs/otmp/Repository/Release1/docs/templates/upload_success.inc,v $
 * $Revision: 1.1 $
 * $Id: upload_success.inc,v 1.1 2001/12/04 23:59:00 hifix Exp $
 *
 * To Do:
 * - LOcalisation
 * - ALL
 */
 ?>
 <p>Text wurde erfolgreich ins System gestellt.<br>
</p>
<p>Bitte w&auml;hlen Sie jetzt die Sprachen in welche der Text &uuml;bersetzt 
  werden soll ..</p>
<p><b><font color="#FF0033">HIER DANN AUFtragserteilung.</font></b></p>
