<? 
/*
 * $Source: /home/xubuntu/berlios_backup/github/tmp-cvs/otmp/Repository/Release1/Release1/user/templates/Attic/forgot_password_success.inc,v $
 * $Revision: 1.1 $
 * $Id: forgot_password_success.inc,v 1.1 2001/12/02 08:23:05 ahlabadi Exp $
 *
 * Password vergessen Form
 *
 * To Do:
 * - Localize
 * - remove javascript or testit
 */
?> 
<p>
Ihr neues Password wird in kürze per mail bei Ihnen eintreffen. Melden Sie sich mit diesem Passwort an und ändern Sie das Passwort dann bitte gleich. 
<BR>
Viel Spaß weiterhin bei OTMP.
</p>
