<? /*
    * $Source: /home/xubuntu/berlios_backup/github/tmp-cvs/otmp/Repository/Release1/user/templates/change_data_success.inc,v $ 
    * $Revision: 1.2 $
    * $Id: change_data_success.inc,v 1.2 2002/01/11 13:13:37 alexgn Exp $
    *
    * File is obsolete?
    */
?> 
<h3 align="left">Sie haben Ihre Daten erfolgreich ge&auml;ndert!</h3>

<p>
Hier gelangen Sie zur&uuml;ck auf die <a href="user_data.php">Benutzerdaten</a> Seite, oder Sie gehen gleich zur <a href="<?=$CFG->wwwroot?>/main.php">Hauptseite</a>.
</p>
<p>Weiterhin viel Spa&szlig; mit OTMP.</p>
