<? /*
    * $Source: /home/xubuntu/berlios_backup/github/tmp-cvs/otmp/Repository/Release1/user/templates/change_password_success.inc,v $ 
    * $Revision: 1.1 $
    * $Id: change_password_success.inc,v 1.1 2001/12/07 18:21:04 alexgn Exp $
    *
    */
?> 
<h3 align="left">Sie haben Ihr Passwort  erfolgreich ge&auml;ndert!</h3>

<p>
Hier gelangen Sie zur&uuml;ck auf die <a href="user_data.php">Benutzerdaten</a> Seite, oder Sie gehen gleich zur <a href="<?=$CFG->wwwroot?>/main.php">Hauptseite</a>.
</p>
<p>Weiterhin viel Spa&szlig; mit OTMP.</p>
