<? 
/*
 * $Source: /home/xubuntu/berlios_backup/github/tmp-cvs/otmp/Repository/Release1/user/templates/forgot_password_success.inc,v $
 * $Revision: 1.1 $
 * $Id: forgot_password_success.inc,v 1.1 2001/11/25 23:21:19 hifix Exp $
 *
 * Password vergessen Form
 *
 * To Do:
 * - Localize
 * - remove javascript or testit
 */
?> 
<p>
Dein neues Password wird in kürze per mail bei Dir eintreffen. Melde Dich mit diesem Passwort an und ändere das Passwort dann bitte gleich. 
<BR>
Viel Spaß weiterhin bei OTMP.
</p>
