<? 
/*
 * $Source: /home/xubuntu/berlios_backup/github/tmp-cvs/otmp/Repository/Release1/user/templates/forgot_password_success.inc,v $
 * $Revision: 1.3 $
 * $Id: forgot_password_success.inc,v 1.3 2001/12/06 16:17:43 hifix Exp $
 *
 * Password vergessen Form
 *
 * To Do:
 * - Localize
 * - remove javascript or testit
 */
?> 
<p>
Ihr neues Password wird in kürze per mail bei Ihnen eintreffen. Melden Sie sich mit diesem Passwort an und ändern Sie das Passwort dann bitte gleich. 
<br>
<a href="<?=$CFG->wwwroot?>/main.php">Hier geht es zur Hauptseite</a>.
</p>
