<? 
/*
 * $Source: /home/xubuntu/berlios_backup/github/tmp-cvs/otmp/Repository/Release1/user/templates/forgot_password_success.inc,v $
 * $Revision: 1.2 $
 * $Id: forgot_password_success.inc,v 1.2 2001/11/29 20:14:14 hifix Exp $
 *
 * Password vergessen Form
 *
 * To Do:
 * - Localize
 * - remove javascript or testit
 */
?> 
<p>
Ihr neues Password wird in kürze per mail bei Ihnen eintreffen. Melden Sie sich mit diesem Passwort an und ändern Sie das Passwort dann bitte gleich. 
<BR>
Viel Spaß weiterhin bei OTMP.
</p>
