<? /*
    * $Source: /home/xubuntu/berlios_backup/github/tmp-cvs/otmp/Repository/Release1/user/templates/signup_success.inc,v $ 
    * $Revision: 1.1 $
    * $Id: signup_success.inc,v 1.1 2001/11/25 23:21:19 hifix Exp $
    *
    */
?> 
<h3 align="left">Anmeldung f&uuml;r OTMP - erfolgreich</h3>
<p>Herzlichen Dank f&uuml;r Ihre Anmeldung. Sie k&ouml;nnen jetzt das System in 
  vollem Umfang benutzen.<br>
  Bitte notieren Sie sich Ihren Usernamen und das Passwort:<br>
</p>
<h4>Login Daten</h4>
<b>Username:</b> <?=$frm['username']?><<br>
<b>Password:</b> <?=$frm['password']?>
<p>
Das Passwort ist an einem sicheren Ort aufzubewahren und nicht weiterzugeben. 
Auch nicht an einen Mitarbeiter von OTMP!
</p>
<p>
Sie k&ouml;nnen sich jetzt mit Deinem Usernamen und Passwort hier <a href="login.php">einloggen</a>, oder zur <a href="../main.php">Hauptseite</a> gehen.
</p>
<p>Viel Spa&szlig; mit OTMP.</p>
